version: "3.7"

services:
    # image project
    app:
        container_name: cuco-app
        build:
            context: .
            dockerfile: Dockerfile
        image: cuco/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        container_name: cuco-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # queue
    queue:
        container_name: cuco-queue
        image: cuco/laravel-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel

    # redis
    redis:
        container_name: cuco-redis
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
